name: 오류 보고
description: "오류를 찾았습니다."
assignees: []
labels: ["오류"]
body:
- type: markdown
  attributes:
    value: |
      "_상세한 오류 보고에 감사드립니다._"
- type: checkboxes
  id: os
  attributes:
    label: 테스트 OS
    description: "오류가 발생하는 기기의 OS를 선택해주세요."
    options:
      - label: Android
      - label: iOS
      - label: 기타
- type: input
  id: device
  attributes:
    label: 테스트 기기 모델명
    description: "오류가 발생하는 테스트 기기의 모델명을 입력해주세요."
    placeholder: "삼성 갤럭시 S20, 아이폰 14 프로"
  validations:
    required: false
- type: input
  id: version
  attributes:
    label: 테스트한 앱의 버전
    description: "버전을 입력하세요."
    placeholder: "1.0.2"
  validations:
    required: true
- type: textarea
  id: desired
  attributes:
    label: 올바른 동작
    description: "오류가 없다면 어떻게 동작해야 하는지 입력해주세요."
  validations:
    required: false
- type: textarea
  id: current
  attributes:
    label: 현재 동작
    description: "현재 어떻게 잘못 동작하는지 입력해주세요."
  validations:
    required: true
- type: textarea
  id: scenario
  attributes:
    label: 재현 순서
    description: 테스트를 진행한 순서를 입력해주세요.
    placeholder: |
      1. "OO" 메뉴로 이동
      2. "OO" 버튼을 클릭
      3. 아래로 스와이프
      4. 오른쪽 상단에 에러 발생
  validations:
    required: false
