name: 오류 보고
description: 소중한 오류보고에 감사드립니다.
title: "[오류] "
labels: []
assignees: []
body:
- type: checkboxes
  id: os
  attributes:
    label: 테스트 OS
    description: "오류가 발생하는 기기의 OS를 선택해주세요."
    options:
      - label: Android
      - label: iOS
- type: input
  id: device
  attributes:
    label: 테스트 기기 모델명
    description: "오류가 발생하는 테스트 기기의 모델명을 입력해주세요."
    placeholder: "삼성 갤럭시 S20, 아이폰 14 프로"
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: 테스트한 앱의 버전을 선택해주세요.
    options:
      - 2.0.0
      - 2.0.1
      - 2.0.2
      - 2.1.0
  validations:
    required: true
- type: textarea
  id: desired
  attributes:
    label: 올바른 동작
    description: "오류가 없다면 어떻게 동작해야 하는지 입력해주세요."
  validations:
    required: false
- type: textarea
  id: current
  attributes:
    label: 현재 동작
    description: "현재 어떻게 동작해야 하는지 입력해주세요."
  validations:
    required: false
- type: textarea
  id: what-happened
  attributes:
    label: 오류를 설명해주세요.
    description: 어떤 부분이 정상적으로 동작하지 않나요?
    placeholder: 오류에 대한 상세한 내용을 기록해 주세요.
    value: "오류설명"
  validations:
    required: true      
- type: textarea
  attributes:
    label: 재현 순서
    description: 오류가 발생한는 순서를 등록해주세요.
    placeholder: |
      1. "OO" 메뉴로 이동
      2. "OO" 버튼을 클릭
      3. 아래로 스와이프
      4. 오른쪽 상단에 에러 발생
  validations:
    required: false 
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com
  validations:
    required: false

- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
