name: 변경 요청
description: "앱을 수정할 필요가 있어요."
assignees: []
labels: ["변경"]
body:
- type: markdown
  attributes:
    value: |
      "_이 버튼의 색상을 #eaeaea로 변경해주세요._"
      "_입력창의 위치를 바꾸어 주세요._"
- type: textarea
  id: current
  attributes:
    label: 현재 상태
    description: "변경이 필요한 위치와 현재 상태를 입력해 주세요."
  validations:
    required: false
- type: textarea
  id: request
  attributes:
    label: 변경 내용
    description: "변경되어야 할 내용을 입력해 주세요."
  validations:
    required: true
