name: 새로운 기능 제안
description: "새로운 기능을 제안합니다."
assignees: []
labels: ["제안"]
body:
- type: markdown
  attributes:
    value: |
      "_매번 이렇게 하는게 불편한데, 이런식으로 하면 더 좋을 거 같아요._"
      "_OO 앱에 OO 메뉴에 있는 것처럼 동작하는게 더 나아 보여요._"
- type: textarea
  id: request
  attributes:
    label: 제안 내용
    description: "더 나은 코드를 위해 기여해 주셔서 감사합니다."
  validations:
    required: true
